Hazelcast Adpater added, closes #3973
utopia-php/cache pull request #28
Opened 2022-10-18 11:08 UTC by kaggrwal

Hazelcast Adpater added, closes #3973

2022-10-28 20:43 UTC, stnguyen90 requested changes
Great PR! 🤯 We left some comments during the review, please check them out. 

Would you please also fix the lining errors?

2022-10-28 20:43 UTC, stnguyen90 commented on phpunit.xml
> +            <file>./tests/Cache/HazelCastTest.php</file>
Incorrect filename

2022-10-28 20:43 UTC, stnguyen90 commented on tests/Cache/HazelCastTest.php
> +use Utopia\Cache\Adapter\Hazelcast as HazelCastAdapter;
No need to rename

2022-10-28 20:43 UTC, stnguyen90 commented on tests/Cache/HazelCastTest.php
> +class HazelCastTest extends Base
This and hte filename should be HazelcastTest

2022-10-30 16:09 UTC, kaggrwal commented
Hi @stnguyen90, I'm getting no issues when running lint on my local. I have attached the screenshot also.
![Screenshot from 2022-10-30 21-38-59](https://user-images.githubusercontent.com/11560407/198889102-cdc2d906-fca9-4c1b-849c-6e59c7510251.png)

2022-10-31 16:32 UTC, PineappleIOnic commented
Thank you so much for the PR 🤩. We're adding the `hacktoberfest-accepted` label to ensure this PR counts towards your Hacktoberfest contributions count. With that said, please stay active on this PR to address any comments once you receive a review. Happy Hacktoberfest! 🎃

2022-10-31 21:48 UTC, stnguyen90 requested changes
> Hi @stnguyen90, I'm getting no issues when running lint on my local. I have attached the screenshot also.

@kaggrwal, running `./vendor/bin/pint` will actually fix your code so that's why running `./vendor/bin/pint --test` after passes. You probably have code you haven't committed or pushed.

2022-11-02 21:28 UTC, stnguyen90 approved these changes
Awesome work on your PR! We've approved your work and it'll be merged soon!

2022-11-30 12:45 UTC, kaggrwal commented
@stnguyen90 Please merge it, as it's been pending since long time.

2022-12-20 19:38 UTC, merged

2022-12-20 19:38 UTC, christyjacob4 commented
THANK YOU! All changes merged 🥳

Please reach out to me on our [Discord server](https://appwrite.io/discord) if you would like to claim your Appwrite swags! As a way of saying thank you, we would also love to invite you to join the Appwrite organization on GitHub. Please share your GitHub username with us on Discord.  

You can accept the invite by visiting https://github.com/orgs/appwrite/invitation. By joining our team, you will officially be an Appwrite maintainer on GitHub.

You can change your membership [visibility settings](https://help.github.com/en/github/setting-up-and-managing-your-github-user-account/publicizing-or-hiding-organization-membership), so your new Appwrite team membership badge will show up on your personal GitHub profile.

Please feel free to look for more PRs you might be interested in helping with on our long list of [Hacktoberfest friendly issues](https://github.com/search?q=org%3Aappwrite+org%3Autopia-php+org%3Aopen-runtimes+label%3Ahacktoberfest+created%3A%3E2021-01-01+state%3Aopen&type=issues&s=updated&o=asc) and help make Appwrite better :)